// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class AccountGroupMapping
    {
        public string AccountId { get; set; }
        public string UserGroupId { get; set; }
        public bool Active { get; set; }
        public string AccountGroupMappingId { get; set; }
    }
}