// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class Account
    {
        public string AccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountPassword { get; set; }
        public string AccountPasswordSha { get; set; }
        public bool Active { get; set; }
    }
}