// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class BarcodeConfig
    {
        public string Id { get; set; }
        public string BarCodeId { get; set; }
        public string ParamName { get; set; }
        public string DataValue { get; set; }
        public string DataType { get; set; }
        public long? Numerical { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}