// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class Barcode
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string StringFormat { get; set; }
        public string LastModiferId { get; set; }
        public string CreatorId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CrationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}