//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{ 

    public partial class Button
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string? NameEn { get; set; }
        public string? Description { get; set; }
        public string? CreatorId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string LastModifierId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public bool Active { get; set; }
    }
}
