// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ContractFile
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string FileContent { get; set; }
        public string ContactId { get; set; }
        public string LastModifierId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? Creationtime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}