// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class Contract
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public long? UserNumber { get; set; }
        public string PaymentTypetime { get; set; }
        public double? ContactValue { get; set; }
        public double? AdvanceMoney { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public bool? StatusPayment { get; set; }
        public string CreatorId { get; set; }
        public string LastModifierId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public string Company { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}