// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class DepartmentStaff
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string DepartmentCode { get; set; }
        public string StaffCode { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}