// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class DeviceSessionDetailWeighing
    {
        public string Id { get; set; }
        public string CodePrint { get; set; }
        public string DeviceId { get; set; }
        public string DeviceType { get; set; }
        public string DeviceSessionId { get; set; }
        public string ProductId { get; set; }
        public string ProductOrder { get; set; }
        public string StatusWt { get; set; }
        public string ReferData { get; set; }
        public string OverData { get; set; }
        public string UnderData { get; set; }
        public string Quantity { get; set; }
        public string Sorted { get; set; }
        public string QuantityHex { get; set; }
        public string QuantityBinarty { get; set; }
        public string CreatorId { get; set; }
        public string LastModifierId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}