// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class DistrictModel
    {
        public DistrictModel()
        {
            WardModel = new HashSet<WardModel>();
        }

        public Guid DistrictId { get; set; }
        public Guid ProvinceId { get; set; }
        public string Appellation { get; set; }
        public string DistrictName { get; set; }
        public string DistrictCode { get; set; }
        public decimal? RegisterVat { get; set; }
        public int? OrderIndex { get; set; }
        public bool Actived { get; set; }
        public string VehicleRegistrationSignature { get; set; }

        public virtual ProvinceModel Province { get; set; }
        public virtual ICollection<WardModel> WardModel { get; set; }
    }
}