// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class Equipment
    {
        public string EquipmentId { get; set; }
        public string EquipmentName { get; set; }
        public string Description { get; set; }
        public string EquipmentGroupId { get; set; }
        public int? Sorted { get; set; }
        public bool Active { get; set; }
        public string PlantId { get; set; }
    }
}