// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ErrorConfig
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string CodeHex { get; set; }
        public string CodeBinary { get; set; }
        public string UnitTyeDriveId { get; set; }
        public long? DataValue { get; set; }
        public string LastModiferId { get; set; }
        public string CreatorId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}