// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class FunctionGroupModuleObjectMapping
    {
        public string FunctionGroupModuleObjectMappingId { get; set; }
        public string ObjectId { get; set; }
        public string Description { get; set; }
        public string ParentId { get; set; }
        public int? Level { get; set; }
        public int? OrderId { get; set; }
        public string Owner { get; set; }
        public bool? Active { get; set; }
        public string ModuleType { get; set; }
        public string GroupType { get; set; }
    }
}