// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using VMSCore.API.EntityModels.Models;

namespace VMSCore.API.EntityModels.Models
{
    public partial interface IEntityDataContextCoreProcedures
    {
        Task<List<GetObjectPermissionByAccountIdResult>> GetObjectPermissionByAccountIdAsync(Guid? AccountId, string typeId, int? type, string moduleType, string groupType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStaffPermissonByStaffIdResult>> GetStaffPermissonByStaffIdAsync(string staffId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
