// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class LineDevice
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string LineCode { get; set; }
        public string DeviceCode { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string WorkshopCode { get; set; }
        public string StageCode { get; set; }
        public Nullable<int> Numerical { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
    }
}