// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class LineDevice
    {
        public string Id { get; set; }
        public string LineId { get; set; }
        public string DeviceId { get; set; }
        public bool? IsManager { get; set; }
        public string WorkshopId { get; set; }
        public string StageId { get; set; }
        public int? Numerical { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }
        public DateTime? LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}