// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class MaterialProduct
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Skupackaging { get; set; }
        public string LineId { get; set; }
        public string Name { get; set; }
        public long? Number { get; set; }
        public string UnitType { get; set; }
        public string Unit { get; set; }
        public string CreatorId { get; set; }
        public string LastModifierId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}