// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class NotificationLine
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string NotiLineContent { get; set; }
        public string IdLine { get; set; }
        public string Lang { get; set; }
        public string IdDrive { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CrationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}