// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ObjectButtonMapping
    {
        public string ObjectButtonMappingId { get; set; }
        public string ObjectId { get; set; }
        public string ButtonId { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    }
}