// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class Plant
    {
        public string PlantName { get; set; }
        public string PlantNameEn { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string CompanyId { get; set; }
        public string PlantId { get; set; }
        public string PlantCode { get; set; }
    }
}