// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ProductionOrder
    {
        public string Code { get; set; }
        public string CompanyId { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string LineId { get; set; }
        public string NumberTemp { get; set; }
        public string CreatorId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public string LastModiferId { get; set; }
        public DateTime? LastModificationTime { get; set; }
        public int? Status { get; set; }
        public int? ParentId { get; set; }
        public int? LevelDate { get; set; }
        public string OrderString { get; set; }
        public string StaffId { get; set; }
        public string StockId { get; set; }
        public string Reason { get; set; }
        public string Lot { get; set; }
        public DateTime? ManufactureDate { get; set; }
        public DateTime? ExpireDate { get; set; }
        public string LinkWeb { get; set; }
        public string ProductionOrderCode { get; set; }
        public Guid Id { get; set; }
    }
}