// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ProductionOrderDetailCode
    {
        public string Id { get; set; }
        public string Code1 { get; set; }
        public string Code2 { get; set; }
        public string ToDate { get; set; }
        public string IdLine { get; set; }
        public string Code { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public bool? Active { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}