// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ProductionOrderDetail
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public int? InboundId { get; set; }
        public int? RefType { get; set; }
        public string DepartmentId { get; set; }
        public string StockId { get; set; }
        public string ProductionOrderId { get; set; }
        public string ModelId { get; set; }
        public string Unit { get; set; }
        public int? Quantity { get; set; }
        public bool? Active { get; set; }
        public string ComanyId { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string LotNumber { get; set; }
        public string LineId { get; set; }
        public string NumberTemp { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationtime { get; set; }
    }
}