// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ProductTypeId { get; set; }
        public string ModelId { get; set; }
        public string ProductGroupId { get; set; }
        public bool Active { get; set; }
        public string TypeId { get; set; }
        public string UnitTypeId { get; set; }
        public string UnitId { get; set; }
        public string ConversionUnit { get; set; }
        public string LastModificationId { get; set; }
        public string CreatorId { get; set; }
        public DateTime? LogDate { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}