//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ProductionOrderRawDetail
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> RefType { get; set; }
        public string ProductionOrderCode { get; set; }
        public string CompanyCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string LotNumber { get; set; }
        public string BatchNumber { get; set; }
        public string LineCode { get; set; }
        public string DeviceCode { get; set; }
        public Nullable<decimal> NumberTemp { get; set; }
        public string UnitCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public Nullable<long> Sorted { get; set; }
        public string CreatorId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string LastModifierId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
