// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class ProvinceModel
    {
        public ProvinceModel()
        {
            DistrictModel = new HashSet<DistrictModel>();
        }

        public Guid ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public string ProvinceCode { get; set; }
        public int? Area { get; set; }
        public int? OrderIndex { get; set; }
        public bool Actived { get; set; }
        public string ConfigPriceCode { get; set; }
        public bool? IsHasLicensePrice { get; set; }

        public virtual ICollection<DistrictModel> DistrictModel { get; set; }
    }
}