// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class Role
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string CompanyId { get; set; }
        public bool? CanDelete { get; set; }
        public string Description { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationTime { get; set; }
    }
}