// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class RoleUser
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string RoleCode { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationtime { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}