// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class RoleUser
    {
        public string Id { get; set; }
        public string RoleId { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public DateTime? CreationTime { get; set; }
        public DateTime? LastModificationtime { get; set; }
    }
}