// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class RoleObjectButtonMapping
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string ObjectCode { get; set; }
        public string ButtonCode { get; set; }
        public string RoleCode { get; set; }
        public string CreatorId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public string LastModifierId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}