// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class StaffAccountMapping
    {
        public string StaffId { get; set; }
        public string AccountId { get; set; }
    }
}