// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class UserGroup
    {
        public string UserGroupId { get; set; }
        public string UserGroupName { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    }
}