// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class WardModel
    {
        public Guid WardId { get; set; }
        public string WardCode { get; set; }
        public string Appellation { get; set; }
        public string WardName { get; set; }
        public Guid? DistrictId { get; set; }
        public int? OrderIndex { get; set; }

        public virtual DistrictModel District { get; set; }
    }
}