// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VMSCore.API.EntityModels.Models
{
    public partial class WorkshopUserMapping
    {
        public string WorkShopId { get; set; }
        public string StaffId { get; set; }
        public string ModuleId { get; set; }
        public bool AllowAccess { get; set; }
        public bool Active { get; set; }
    }
}