//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VMSCore.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản.
        /// </summary>
        public static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Actived {
            get {
                return ResourceManager.GetString("Actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngưng sử dụng.
        /// </summary>
        public static string Actived_False {
            get {
                return ResourceManager.GetString("Actived_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang sử dụng.
        /// </summary>
        public static string Actived_True {
            get {
                return ResourceManager.GetString("Actived_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to và.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string Appellation {
            get {
                return ResourceManager.GetString("Appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hẹn.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ hẹn.
        /// </summary>
        public static string AppointmentTime {
            get {
                return ResourceManager.GetString("AppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấp nhận.
        /// </summary>
        public static string Btn_Accept {
            get {
                return ResourceManager.GetString("Btn_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Btn_AddRow {
            get {
                return ResourceManager.GetString("Btn_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string Btn_Choose {
            get {
                return ResourceManager.GetString("Btn_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn làm hình đại diện.
        /// </summary>
        public static string Btn_ChooseImageFirst {
            get {
                return ResourceManager.GetString("Btn_ChooseImageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hình ảnh.
        /// </summary>
        public static string Btn_EditImage {
            get {
                return ResourceManager.GetString("Btn_EditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Btn_Import {
            get {
                return ResourceManager.GetString("Btn_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Btn_Login {
            get {
                return ResourceManager.GetString("Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu và tiếp tục.
        /// </summary>
        public static string Btn_SaveAndContinue {
            get {
                return ResourceManager.GetString("Btn_SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string Btn_View {
            get {
                return ResourceManager.GetString("Btn_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền chức năng.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Permission_AccountModel {
            get {
                return ResourceManager.GetString("Permission_AccountModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string Permission_ChangePassword {
            get {
                return ResourceManager.GetString("Permission_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string Permission_FunctionModel {
            get {
                return ResourceManager.GetString("Permission_FunctionModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hệ thống.
        /// </summary>
        public static string Permission_Login {
            get {
                return ResourceManager.GetString("Permission_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Permission_Logout {
            get {
                return ResourceManager.GetString("Permission_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Permission_MenuModel {
            get {
                return ResourceManager.GetString("Permission_MenuModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màn hình.
        /// </summary>
        public static string Permission_MobileScreen {
            get {
                return ResourceManager.GetString("Permission_MobileScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức năng.
        /// </summary>
        public static string Permission_PageModel {
            get {
                return ResourceManager.GetString("Permission_PageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        public static string Permission_RolesModel {
            get {
                return ResourceManager.GetString("Permission_RolesModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string Province_Area {
            get {
                return ResourceManager.GetString("Province_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tỉnh thành.
        /// </summary>
        public static string Province_ProvinceCode {
            get {
                return ResourceManager.GetString("Province_ProvinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tỉnh thành.
        /// </summary>
        public static string Province_ProvinceName {
            get {
                return ResourceManager.GetString("Province_ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/thành phố.
        /// </summary>
        public static string ProvinceId {
            get {
                return ResourceManager.GetString("ProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/thành phố.
        /// </summary>
        public static string ProvinceName {
            get {
                return ResourceManager.GetString("ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin &quot;{0}&quot;.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset dữ liệu thành công!.
        /// </summary>
        public static string ResetData_Success {
            get {
                return ResourceManager.GetString("ResetData_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string ResourceComment {
            get {
                return ResourceManager.GetString("ResourceComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string ResourceKey {
            get {
                return ResourceManager.GetString("ResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string ResourceValue {
            get {
                return ResourceManager.GetString("ResourceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn chế.
        /// </summary>
        public static string Restriction {
            get {
                return ResourceManager.GetString("Restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Chọn khu vực--.
        /// </summary>
        public static string Select_area {
            get {
                return ResourceManager.GetString("Select_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Chọn quận/huyện--.
        /// </summary>
        public static string Select_district {
            get {
                return ResourceManager.GetString("Select_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Chọn tỉnh/tp--.
        /// </summary>
        public static string Select_provice {
            get {
                return ResourceManager.GetString("Select_provice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học viên.
        /// </summary>
        public static string StopStudent {
            get {
                return ResourceManager.GetString("StopStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string Store_CompanyId {
            get {
                return ResourceManager.GetString("Store_CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái.
        /// </summary>
        public static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lên.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe đã sử dụng.
        /// </summary>
        public static string UsedMaterial {
            get {
                return ResourceManager.GetString("UsedMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản dùng để đăng nhập.
        /// </summary>
        public static string UserName_Hint {
            get {
                return ResourceManager.GetString("UserName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phương tiện.
        /// </summary>
        public static string VehicleCode {
            get {
                return ResourceManager.GetString("VehicleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương tiện đi lại.
        /// </summary>
        public static string VehicleId {
            get {
                return ResourceManager.GetString("VehicleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại xe.
        /// </summary>
        public static string VehicleInfo_ProductHierarchyCode {
            get {
                return ResourceManager.GetString("VehicleInfo_ProductHierarchyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhãn hiệu.
        /// </summary>
        public static string VehicleInfo_ProfitCenterCode {
            get {
                return ResourceManager.GetString("VehicleInfo_ProfitCenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin xe.
        /// </summary>
        public static string VehicleInformation {
            get {
                return ResourceManager.GetString("VehicleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phương tiện.
        /// </summary>
        public static string VehicleName {
            get {
                return ResourceManager.GetString("VehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy khai đăng ký xe.
        /// </summary>
        public static string VehicleRegisterDeclaration {
            get {
                return ResourceManager.GetString("VehicleRegisterDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy đăng ký xe.
        /// </summary>
        public static string VehicleRegisterDeclaration_ShortText {
            get {
                return ResourceManager.GetString("VehicleRegisterDeclaration_ShortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vuong.
        /// </summary>
        public static string vuong {
            get {
                return ResourceManager.GetString("vuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phường xã.
        /// </summary>
        public static string Ward_Appellation {
            get {
                return ResourceManager.GetString("Ward_Appellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường.
        /// </summary>
        public static string Ward_Phuong {
            get {
                return ResourceManager.GetString("Ward_Phuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thị trấn.
        /// </summary>
        public static string Ward_ThiTran {
            get {
                return ResourceManager.GetString("Ward_ThiTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xã.
        /// </summary>
        public static string Ward_Xa {
            get {
                return ResourceManager.GetString("Ward_Xa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phường xã.
        /// </summary>
        public static string WardCode {
            get {
                return ResourceManager.GetString("WardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường/xã.
        /// </summary>
        public static string WardId {
            get {
                return ResourceManager.GetString("WardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phường xã.
        /// </summary>
        public static string WardName {
            get {
                return ResourceManager.GetString("WardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty.
        /// </summary>
        public static string WERKS {
            get {
                return ResourceManager.GetString("WERKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
