//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroupMapping
    {
        public string AccountId { get; set; }
        public string UserGroupId { get; set; }
        public bool Active { get; set; }
        public string AccountGroupMappingId { get; set; }
    }
}
