//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string AccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountPassword { get; set; }
        public string AccountPasswordSHA { get; set; }
        public bool Active { get; set; }
    }
}
