//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceSessionDetail
    {
        public string Id { get; set; }
        public string CodePrint { get; set; }
        public string DeviceId { get; set; }
        public string DeviceSessionId { get; set; }
        public string Quantity { get; set; }
        public string Sorted { get; set; }
        public string QuantityHex { get; set; }
        public string QuantityBinary { get; set; }
        public string CreatorId { get; set; }
        public string LastModifierId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
    }
}
