//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceConnectHistory
    {
        public string Id { get; set; }
        public string DeviceId { get; set; }
        public string DeviceType { get; set; }
        public string DeviceGroup { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string KeyTime { get; set; }
        public string KeyDate { get; set; }
        public string CreatorId { get; set; }
        public string LastModifierId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
    }
}
