//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistrictModel()
        {
            this.WardModel = new HashSet<WardModel>();
        }
    
        public System.Guid DistrictId { get; set; }
        public System.Guid ProvinceId { get; set; }
        public string Appellation { get; set; }
        public string DistrictName { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<decimal> RegisterVAT { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public bool Actived { get; set; }
        public string VehicleRegistrationSignature { get; set; }
    
        public virtual ProvinceModel ProvinceModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WardModel> WardModel { get; set; }
    }
}
