//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionGroupModuleObjectMapping
    {
        public string FunctionGroupModuleObjectMappingId { get; set; }
        public string ObjectId { get; set; }
        public string Description { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Owner { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ModuleType { get; set; }
        public string GroupType { get; set; }
    }
}
