//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryModel
    {
        public System.Guid HistoryModifyId { get; set; }
        public Nullable<System.Guid> PageId { get; set; }
        public Nullable<System.Guid> FieldId { get; set; }
        public string FieldCode { get; set; }
        public string FieldName { get; set; }
        public string OldData { get; set; }
        public string LastModifiedUser { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
    }
}
