//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginCheck
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string DeviceName { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<decimal> SessionDuration { get; set; }
        public Nullable<int> Sorted { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
