//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINE_SYNC_LOG
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TypeGiaoDich { get; set; }
        public string MethodName { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string ApiKey { get; set; }
        public string TokenCode { get; set; }
        public string JsonSend { get; set; }
        public string JsonReceiv { get; set; }
        public string DeviceName { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<long> Sorted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
