//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLine
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string NotiLineContent { get; set; }
        public string IdLine { get; set; }
        public string Lang { get; set; }
        public string IdDrive { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> CrationTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
    }
}
