//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALLETDEFINE_TRANS
    {
        public System.Guid Id { get; set; }
        public string KeyPallet { get; set; }
        public string KeyBox { get; set; }
        public string LenhSanXuat { get; set; }
        public string StockID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string LOT { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> UnitConvert { get; set; }
        public Nullable<decimal> CurrentQty { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string KeyDate { get; set; }
        public string KeyTime { get; set; }
        public string Description { get; set; }
        public Nullable<long> Sorted { get; set; }
        public Nullable<long> SortedBox { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public bool Active { get; set; }
    }
}
