//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantUserMapping
    {
        public string PlantId { get; set; }
        public string StaffId { get; set; }
        public string MduleId { get; set; }
        public bool AllowAccess { get; set; }
        public bool Active { get; set; }
    }
}
