//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrderDetailMAP
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string KeyBox { get; set; }
        public string KeyCuon { get; set; }
        public Nullable<int> LevelBox { get; set; }
        public Nullable<int> LevelCuon { get; set; }
        public string ProductionOrderCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string LOT { get; set; }
        public string UnitCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string KeyDate { get; set; }
        public string KeyTime { get; set; }
        public string Description { get; set; }
        public Nullable<long> Sorted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    }
}
