//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionOrder
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string LineCode { get; set; }
        public Nullable<decimal> NumberTemp { get; set; }
        public Nullable<long> Sorted { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> LevelPP { get; set; }
        public string OrderString { get; set; }
        public string StaffCode { get; set; }
        public string StockId { get; set; }
        public string Reason { get; set; }
        public string Lot { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string LinkWeb { get; set; }
    }
}
