//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUser
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string RoleCode { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string CreatorId { get; set; }
        public string LastModifierId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationtime { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
