//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSCore.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusConfig
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public string NameShow { get; set; }
        public string CodeHex { get; set; }
        public string CodeBinary { get; set; }
        public Nullable<int> DecimalCode { get; set; }
        public string CodeMap { get; set; }
        public string TypeDeviceCode { get; set; }
        public string DeviceGroupCode { get; set; }
        public Nullable<int> Level { get; set; }
        public string LastModifierId { get; set; }
        public string CreatorId { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
    }
}
